/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    AppLogos: typeof import('./../components/AppLogos.vue')['default']
    HiCounter: typeof import('./../components/HiCounter.vue')['default']
    InputEntry: typeof import('./../components/InputEntry.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AppFooter: typeof import('./../components/AppFooter.vue')['default']
  const AppLogos: typeof import('./../components/AppLogos.vue')['default']
  const HiCounter: typeof import('./../components/HiCounter.vue')['default']
  const InputEntry: typeof import('./../components/InputEntry.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}